# Generated by Django 3.1 on 2020-08-09 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('Age', models.PositiveIntegerField(null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', phone_field.models.PhoneField(help_text='Enter Your Contact Number', max_length=31, null=True)),
                ('address', models.CharField(max_length=512, null=True)),
                ('user_type', models.CharField(choices=[('administrator', 'administrator'), ('professor', 'professor'), ('Lab Tech', 'Lab Tech'), ('Normal_user', 'Normal_user')], max_length=16, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
