# Generated by Django 3.1 on 2020-08-09 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
        migrations.CreateModel(
            name='personal_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('bloodgroup', models.CharField(choices=[('a+', 'A+'), ('o+', 'O+'), ('b+', 'B+'), ('ab+', 'AB+'), ('a-', 'A-'), ('o-', 'O-'), ('b-', 'B-'), ('ab-', 'AB-')], max_length=12, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('father_name', models.CharField(max_length=128, null=True)),
                ('father_occupation', models.CharField(max_length=128, null=True)),
                ('mother_name', models.CharField(max_length=128, null=True)),
                ('mother_occupation', models.CharField(max_length=128, null=True)),
                ('religion', models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('others', 'others')], max_length=20, null=True)),
                ('nationality', models.CharField(choices=[('Indian', 'Indian'), ('American', 'American'), ('Chinese', 'Chinese'), ('Russian', 'Russian')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Door_Number', models.CharField(max_length=150)),
                ('Street', models.CharField(max_length=150)),
                ('Address_Line_1', models.CharField(max_length=150)),
                ('Address_line_2', models.CharField(max_length=150)),
                ('Land_Mark', models.CharField(max_length=150)),
                ('Pincode', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
