# Generated by Django 3.1 on 2020-08-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200816_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='Address_Type',
            field=models.CharField(choices=[('residential', 'residential'), ('work', 'work')], max_length=64, null=True),
        ),
    ]
